name: Build and Push Docker Image  # 任务名称：构建并推送 Docker 镜像

on:
  push:
    branches:
      - main  # 当代码推送到主分支时触发任务

jobs:
  build:
    runs-on: ubuntu-latest  # 在最新版 Ubuntu 上运行任务

    steps:
    - name: Checkout repository  # 步骤：检出代码仓库
      uses: actions/checkout@v2  # 使用 GitHub 提供的 checkout 动作（动作版本 2）

    - name: Set up Docker Buildx  # 步骤：设置 Docker Buildx
      uses: docker/setup-buildx-action@v1  # 使用 Docker 提供的 setup-buildx-action 动作（版本 1）

    - name: Cache Docker layers  # 步骤：缓存 Docker 层
      uses: actions/cache@v2  # 使用 GitHub 提供的缓存动作（版本 2）
      with:
        path: /tmp/.buildx-cache  # 缓存路径
        key: ${{ runner.os }}-buildx-${{ github.sha }}  # 缓存键
        restore-keys: |  # 恢复密钥列表
          ${{ runner.os }}-buildx-

    - name: Log in to Docker Hub  # 步骤：登录到 Docker Hub
      uses: docker/login-action@v2  # 使用 Docker 提供的 login-action 动作（版本 2）
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # 使用 GitHub 密钥存储的 Docker 用户名
        password: ${{ secrets.DOCKER_PASSWORD }}  # 使用 GitHub 密钥存储的 Docker 密码

    - name: Build and push Docker image  # 步骤：构建并推送 Docker 镜像
      uses: docker/build-push-action@v2  # 使用 Docker 提供的 build-push-action 动作（版本 2）
      with:
        context: .  # Docker 上下文路径
        file: ./Dockerfile  # Dockerfile路径
        push: true  # 执行推送操作
        tags: ${{ secrets.DOCKER_USERNAME }}/dbfrontend:latest  # Docker 镜像标签

    - name: Logout from Docker Hub  # 步骤：从 Docker Hub 注销
      run: docker logout  # 执行 docker 注销命令
